/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("io.dropwizard.metrics:metrics-core:3.2.6")
    testImplementation(project(":flink-metrics-core"))
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-test-utils-junit"))
    compileOnly(project(":flink-annotations"))
    compileOnly(project(":flink-metrics-core"))
}

description = "Flink : Metrics : Dropwizard"
