/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-streaming-java"))
    implementation("org.schwering:irclib:1.10")
}

description = "Flink : Contrib : Connectors : Wikiedits"
