/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-end-to-end-tests-common"))
    implementation("org.apache.flink:flink-shaded-guava:30.1.1-jre-14.0")
    implementation(project(":flink-connector-kinesis"))
    implementation(project(":flink-connector-kinesis"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-json-glue-schema-registry_2.12"))
    implementation("junit:junit:4.13.2")
}

description = "Flink : E2E Tests : JSON AWS Glue Schema Registry"
