/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

val testArtifacts: Configuration by configurations.creating

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-connector-files"))
    implementation("org.apache.commons:commons-lang3:3.3.2")
    implementation("org.apache.flink:flink-shaded-asm-7:7.1-14.0")
    testImplementation(project(":flink-core", "testArtifacts"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation("com.esotericsoftware.kryo:kryo:2.24.0")
    compileOnly("com.ibm.icu:icu4j:67.1")
}

description = "Flink : Table : Common"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

artifacts {
    add("testArtifacts", testsJar)
}
