/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.apache.orc:orc-core:1.5.6")
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-file-sink-common"))
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-table-runtime_2.12"))
    compileOnly("org.apache.commons:commons-lang3:3.3.2")
    compileOnly("org.apache.hadoop:hadoop-common:2.4.1")
    compileOnly("org.apache.hadoop:hadoop-hdfs:2.4.1")
}

description = "Flink : Formats : Orc"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
