/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-statebackend-rocksdb"))
    testImplementation(project(":flink-statebackend-rocksdb"))
    testImplementation(project(":flink-test-utils"))
    testImplementation("org.apache.curator:curator-test:2.12.0")
    testImplementation(project(":flink-runtime"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-runtime"))
    compileOnly(project(":flink-queryable-state-client-java"))
    compileOnly("org.apache.flink:flink-shaded-netty:4.1.65.Final-14.0")
}

description = "Flink : Queryable state : Runtime"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
