/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-table-api-java-bridge"))
    implementation(project(":flink-table-api-scala-bridge_2.12"))
    implementation(project(":flink-table-planner_2.12"))
    implementation(project(":flink-csv"))
    implementation(project(":flink-streaming-scala_2.12"))
    implementation(project(":flink-clients"))
    testImplementation(project(":flink-test-utils"))
}

description = "Flink : Examples : Table"
