/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    compileOnly(project(":flink-core"))
}

description = "Flink : E2E Tests : Plugins : Another dummy fs"
