/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-table-api-java"))
    implementation(project(":flink-java"))
    implementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-table-api-java"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : Table : API Java bridge"
