/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-streaming-java"))
    compileOnly("commons-cli:commons-cli:1.5.0")
    implementation(project(":flink-rpc-core"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-core"))
}

description = "Flink : Container"
