/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-streaming-java"))
    compileOnly(project(":flink-runtime"))
    compileOnly(project(":flink-clients"))
}

description = "Flink : Container"
