/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-connector-gcp-pubsub"))
    testImplementation("com.spotify:docker-client:8.16.0")
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : E2E Tests : Connectors : Google PubSub"
