/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-elasticsearch-base"))
    testImplementation(project(":flink-connector-elasticsearch-base", "testArtifacts"))
    implementation("org.elasticsearch.client:transport:5.3.3")
    implementation("io.netty:netty-buffer:4.1.46.Final")
    implementation("io.netty:netty-codec:4.1.46.Final")
    implementation("io.netty:netty-codec-http:4.1.46.Final")
    implementation("io.netty:netty-common:4.1.46.Final")
    implementation("io.netty:netty-handler:4.1.46.Final")
    implementation("io.netty:netty-resolver:4.1.46.Final")
    implementation("io.netty:netty-transport:4.1.46.Final")
    testImplementation(project(":flink-test-utils"))
    implementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-connector-elasticsearch-base"))
    compileOnly(project(":flink-streaming-java"))
    implementation(project(":flink-core"))
}

description = "Flink : Connectors : Elasticsearch 5"
