/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-table-common"))
    implementation(project(":flink-table-api-java"))
    implementation(project(":flink-table-api-java-bridge"))
    implementation(project(":flink-table-code-splitter"))
    implementation("org.codehaus.janino:janino:3.0.11")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-table-common"))
    providedCompile(project(":flink-streaming-java"))
    providedCompile(project(":flink-cep"))
    providedCompile(project(":flink-scala_2.12"))
}

description = "Flink : Table : Runtime"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
