/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-orc_2.12"))
}

description = "Flink : Formats : SQL Orc"
