/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.apache.nifi:nifi-site-to-site-client:1.14.0")
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-tests"))
    providedCompile(project(":flink-streaming-java"))
}

description = "Flink : Connectors : Nifi"
