/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-end-to-end-tests-common"))
    implementation(project(":flink-connector-pulsar"))
    implementation(project(":flink-connector-pulsar"))
    implementation("org.testcontainers:pulsar:1.16.2")
}

description = "Flink : E2E Tests : Pulsar"
