/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-java"))
    implementation(project(":flink-scala_2.12"))
    implementation(project(":flink-clients"))
}

description = "Flink : Examples : Batch"
