/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-java"))
    implementation(project(":flink-scala_2.12"))
    implementation(project(":flink-clients"))
    implementation("commons-io:commons-io:2.11.0")
    implementation("org.apache.commons:commons-lang3:3.3.2")
}

description = "Flink : Examples : Batch"
