/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-test-utils-junit"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-rpc-akka-loader"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-streaming-java"))
    implementation("io.netty:netty:3.10.6.Final")
    implementation("org.apache.curator:curator-test:2.12.0")
    implementation("org.apache.hadoop:hadoop-minikdc:3.2.0")
    runtimeOnly(project(":flink-statebackend-changelog"))
}

description = "Flink : Test utils : Utils"
