/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.apache.beam:beam-runners-java-fn-execution:2.27.0")
    implementation("org.apache.beam:beam-runners-core-java:2.27.0")
    implementation("com.google.protobuf:protobuf-java:3.17.3")
    implementation("net.sf.py4j:py4j:0.10.8.1")
    implementation("net.razorvine:pyrolite:4.13")
    implementation("org.apache.arrow:arrow-vector:0.16.0")
    implementation("io.netty:netty-buffer:4.1.46.Final")
    implementation("io.netty:netty-common:4.1.46.Final")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-table-runtime_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-test-utils-junit"))
    providedCompile(project(":flink-core"))
    providedCompile(project(":flink-clients"))
    providedCompile(project(":flink-java"))
    providedCompile(project(":flink-streaming-java"))
    providedCompile(project(":flink-table-common"))
    providedCompile(project(":flink-table-planner_2.12"))
    providedCompile(project(":flink-table-runtime_2.12"))
}

description = "Flink : Python"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
