/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-examples-batch_2.12"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-java"))
}

description = "Flink : E2E Tests : High parallelism iterations"
