/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-elasticsearch-base"))
    implementation("org.elasticsearch.client:elasticsearch-rest-high-level-client:7.5.1")
    testImplementation("org.testcontainers:elasticsearch:1.16.2")
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-connector-elasticsearch-base"))
    testImplementation("org.elasticsearch.client:transport:7.5.1")
    testImplementation("org.elasticsearch.plugin:transport-netty4-client:7.5.1")
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-json"))
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-table-api-java-bridge"))
}

description = "Flink : Connectors : Elasticsearch 7"
