/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("com.h2database:h2:1.4.200")
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation("com.opentable.components:otj-pg-embedded:0.13.4")
    testImplementation("org.testcontainers:postgresql:1.16.2")
    testImplementation("ch.vorburger.mariaDB4j:mariaDB4j:2.4.0")
    testImplementation("org.mariadb.jdbc:mariadb-java-client:2.7.4")
    testImplementation("mysql:mysql-connector-java:8.0.27")
    testImplementation("org.apache.derby:derby:10.14.2.0")
    testImplementation("org.testcontainers:mysql:1.16.2")
    compileOnly(project(":flink-table-api-java-bridge"))
    compileOnly("org.postgresql:postgresql:42.2.10")
}

description = "Flink : Connectors : JDBC"
