/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

val testArtifacts: Configuration by configurations.creating

dependencies {
    implementation("org.apache.flink:flink-shaded-guava:30.1.1-jre-14.0")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-connector-files"))
    testImplementation(project(":flink-core", "testArtifacts"))
    testImplementation("com.esotericsoftware.kryo:kryo:2.24.0")
    testImplementation("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
    testImplementation("org.apache.hadoop:hadoop-common:2.4.1")
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-streaming-java", "testArtifacts"))
    testImplementation(project(":flink-optimizer", "testArtifacts"))
    testImplementation(project(":flink-rpc-core"))
    testImplementation(project(":flink-runtime", "testArtifacts"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-java"))
    testImplementation(project(":flink-scala_2.12"))
    testImplementation(project(":flink-scala_2.12"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-examples-batch_2.12"))
    testImplementation(project(":flink-java"))
    testImplementation(project(":flink-hadoop-compatibility_2.12"))
    testImplementation(project(":flink-hadoop-compatibility_2.12"))
    testImplementation(project(":flink-optimizer"))
    testImplementation(project(":flink-runtime"))
    testImplementation("org.apache.curator:curator-test:2.12.0")
    testImplementation("org.scalatest:scalatest_2.12:3.0.0")
    testImplementation("joda-time:joda-time:2.5")
    testImplementation("org.joda:joda-convert:1.7")
    testImplementation(project(":flink-statebackend-rocksdb"))
    testImplementation(project(":flink-statebackend-rocksdb"))
    testImplementation(project(":flink-dstl-dfs"))
    testImplementation("com.github.oshi:oshi-core:3.4.0")
    testImplementation("org.reflections:reflections:0.9.10")
    testImplementation("org.apache.commons:commons-lang3:3.3.2")
    testImplementation("org.apache.flink:flink-shaded-guava:30.1.1-jre-14.0")
    testImplementation("org.apache.flink:flink-shaded-netty:4.1.65.Final-14.0")
    testImplementation(project(":flink-queryable-state-client-java"))
    testImplementation(project(":flink-file-sink-common"))
    testImplementation(project(":flink-statebackend-rocksdb"))
    testImplementation("com.ververica:frocksdbjni:6.20.3-ververica-1.0")
}

description = "Flink : Tests"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
