/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-test-utils-junit"))
    implementation("junit:junit:4.13.2")
}

description = "Flink : Test utils : Connectors"
