/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-streaming-scala_2.12"))
    implementation(project(":flink-table-common"))
    implementation(project(":flink-table-api-java"))
    implementation(project(":flink-table-api-java-bridge"))
    implementation(project(":flink-table-planner_2.12"))
    implementation(project(":flink-table-runtime_2.12"))
    implementation("org.jline:jline-terminal:3.9.0")
    implementation("org.jline:jline-reader:3.9.0")
    implementation("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-csv"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-python_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-connector-hive_2.12"))
    testImplementation(project(":flink-hadoop-compatibility_2.12"))
    testImplementation("org.apache.hive:hive-metastore:2.3.4")
    testImplementation("org.apache.hive:hive-exec:2.3.4")
    testImplementation("org.apache.hadoop:hadoop-common:2.7.5")
    providedCompile(project(":flink-connector-hive_2.12"))
    compileOnly("org.apache.hadoop:hadoop-mapreduce-client-core:2.7.5")
}

description = "Flink : Table : SQL Client"
