/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-datastream-allround-test"))
    implementation(project(":flink-test-utils"))
}

description = "Flink : E2E Tests : Heavy deployment"
