/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.scala-lang:scala-library:2.12.7")
    implementation("org.scala-lang:scala-compiler:2.12.7")
    implementation("com.typesafe.akka:akka-actor_2.12:2.6.15")
    implementation("com.typesafe.akka:akka-remote_2.12:2.6.15")
    implementation("com.typesafe.akka:akka-slf4j_2.12:2.6.15")
    implementation("io.netty:netty:3.10.6.Final")
    implementation("org.clapper:grizzled-slf4j_2.12:1.3.2")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-core"))
    providedCompile(project(":flink-core"))
    providedCompile(project(":flink-rpc-core"))
    compileOnly("org.apache.flink:flink-shaded-netty:4.1.65.Final-14.0")
}

description = "Flink : RPC : Akka"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
