/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("com.rabbitmq:amqp-client:5.13.1")
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-test-utils"))
    testImplementation("org.testcontainers:rabbitmq:1.16.2")
    providedCompile(project(":flink-streaming-java"))
}

description = "Flink : Connectors : RabbitMQ"
