/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-kinesis"))
}

description = "Flink : Connectors : SQL : Kinesis"
