/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("com.esotericsoftware.kryo:kryo:2.24.0")
    implementation("org.apache.avro:avro:1.10.0")
    testImplementation(project(":flink-streaming-scala_2.12"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-scala_2.12"))
    testImplementation(project(":flink-scala_2.12"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-file-sink-common"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-table-common"))
    compileOnly("joda-time:joda-time:2.5")
}

description = "Flink : Formats : Avro"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
