/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    compileOnly(project(":flink-java"))
    compileOnly(project(":flink-table-planner_2.12"))
}

description = "Flink : E2E Tests : TPCDS"
