/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-s3-fs-base"))
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-hadoop-fs"))
    providedCompile(project(":flink-core"))
    compileOnly("javax.xml.bind:jaxb-api:2.3.1")
}

description = "Flink : FileSystems : S3 FS Hadoop"
