/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-table-common"))
    implementation(project(":flink-table-api-java"))
    implementation("org.scala-lang:scala-reflect:2.12.7")
    implementation("org.scala-lang:scala-library:2.12.7")
    implementation("org.scala-lang:scala-compiler:2.12.7")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-api-java"))
}

description = "Flink : Table : API Scala"
