/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
    id("scala")
}

dependencies {
    api(project(":flink-table-common"))
    api(project(":flink-table-api-java"))
    api("org.scala-lang:scala-reflect:2.12.7")
    api("org.scala-lang:scala-library:2.12.7")
    api("org.scala-lang:scala-compiler:2.12.7")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-api-java"))
}

description = "Flink : Table : API Scala"
