/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-end-to-end-tests-common"))
    implementation(project(":flink-test-utils-junit"))
    implementation("org.apache.kafka:kafka-clients:2.8.1")
    implementation("org.testcontainers:kafka:1.16.2")
    implementation(project(":flink-connector-testing"))
    implementation(project(":flink-connector-kafka"))
    testImplementation(project(":flink-sql-client-test"))
    testImplementation(project(":flink-sql-avro"))
    testImplementation(project(":flink-sql-avro-confluent-registry"))
    testImplementation("io.confluent:kafka-avro-serializer:5.5.2")
    testImplementation("io.confluent:kafka-schema-registry-client:5.5.2")
    testImplementation("org.apache.avro:avro:1.10.0")
    providedCompile(project(":flink-streaming-kafka-test"))
}

description = "Flink : E2E Tests : Common Kafka"
