/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("scala")
    id("org.apache.flink.java-conventions")
}

dependencies {
    api(project(":flink-core"))
    api(project(":flink-streaming-java"))
    implementation(project(":flink-java"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-scala_2.12"))
    implementation("com.esotericsoftware.kryo:kryo:2.24.0")
    implementation("org.scala-lang:scala-reflect:2.12.7")
    implementation("org.scala-lang:scala-library:2.12.7")
    implementation("org.scala-lang:scala-compiler:2.12.7")
    testImplementation("org.scalatest:scalatest_2.12:3.0.0")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-streaming-java", "testArtifacts"))
    testImplementation(project(":flink-tests", "testArtifacts"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-file-sink-common"))
}

description = "Flink : Streaming Scala"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

sourceSets {
    named("main") {
        withConvention(ScalaSourceSet::class) {
            scala {
                setSrcDirs(listOf("src/main/scala", "src/main/java"))
            }
        }
        java {
            setSrcDirs(emptyList<String>())
        }
    }
    named("test") {
        withConvention(ScalaSourceSet::class) {
            scala {
                setSrcDirs(listOf("src/test/scala", "src/test/java"))
            }
        }
        java {
            setSrcDirs(emptyList<String>())
        }
    }
}
