/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    api(project(":flink-table-common"))
    api(project(":flink-core"))
    implementation("com.esotericsoftware.kryo:kryo:2.24.0")
    implementation("org.apache.commons:commons-lang3:3.3.2")
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : Table : API Java"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
