/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-base"))
    implementation("org.apache.kafka:kafka-clients:2.8.1")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation("org.apache.kafka:kafka_2.12:2.8.1")
    testImplementation("org.apache.zookeeper:zookeeper:3.5.9")
    testImplementation("org.testcontainers:kafka:1.16.2")
    testImplementation(project(":flink-tests"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-connector-test-utils"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-metrics-jmx"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-json"))
    testImplementation(project(":flink-avro"))
    testImplementation(project(":flink-avro-confluent-registry"))
    testImplementation(project(":flink-csv"))
    testImplementation(project(":flink-connector-testing"))
    providedCompile(project(":flink-streaming-java"))
    providedCompile(project(":flink-table-api-java-bridge"))
}

description = "Flink : Connectors : Kafka"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
