/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("io.confluent:kafka-schema-registry-client:5.5.2")
    implementation(project(":flink-avro"))
    testImplementation(project(":flink-table-api-java"))
    testImplementation(project(":flink-table-runtime_2.12"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-avro"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-table-api-java"))
    compileOnly(project(":flink-table-common"))
}

description = "Flink : Formats : Avro confluent registry"
