/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-hive_2.12"))
    implementation("org.apache.hive:hive-exec:1.2.2")
    implementation("org.apache.hive:hive-metastore:1.2.2")
    implementation("org.apache.thrift:libfb303:0.9.2")
    implementation("org.apache.orc:orc-core:1.5.6")
    implementation("org.apache.orc:orc-shims:1.5.6")
    implementation("io.airlift:aircompressor:0.8")
    implementation("org.antlr:antlr-runtime:3.5.2")
}

description = "Flink : Connectors : SQL : Hive 1.2.2"
