/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-avro"))
    implementation("software.amazon.glue:schema-registry-serde:1.1.5")
    implementation("software.amazon.glue:schema-registry-common:1.1.5")
    compileOnly(project(":flink-core"))
}

description = "Flink : Formats : Avro AWS Glue Schema Registry"
