/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-python_2.12"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-java"))
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-table-api-java-bridge"))
}

description = "Flink : E2E Tests : Python"
