/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-lang3:3.11")
    implementation("org.apache.flink:flink-shaded-guava:30.1.1-jre-14.0")
    implementation(project(":flink-core"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-statebackend-rocksdb"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-streaming-java"))
}

description = "Flink : Libraries : CEP"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
