/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation("com.squareup.okhttp3:okhttp:3.14.9")
    implementation("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
    implementation(project(":flink-test-utils-junit"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-connector-testing"))
    implementation("org.testcontainers:testcontainers:1.16.2")
    providedCompile(project(":flink-dist_2.12"))
}

description = "Flink : E2E Tests : Common"
