/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-avro-confluent-registry"))
}

description = "Flink : Formats : SQL Avro Confluent Registry"
