/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-metrics-dropwizard"))
    implementation("io.dropwizard.metrics:metrics-core:3.2.6")
    implementation("io.dropwizard.metrics:metrics-graphite:3.2.6")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-metrics-core"))
    providedCompile(project(":flink-annotations"))
    providedCompile(project(":flink-metrics-core"))
}

description = "Flink : Metrics : Graphite"
