/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-runtime"))
    implementation(project(":flink-clients"))
    implementation("org.apache.hadoop:hadoop-common:2.4.1")
    implementation("org.apache.hadoop:hadoop-hdfs:2.4.1")
    implementation("org.apache.hadoop:hadoop-yarn-common:2.4.1")
    implementation("org.apache.hadoop:hadoop-yarn-client:2.4.1")
    implementation("org.apache.hadoop:hadoop-mapreduce-client-core:2.4.1")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-runtime"))
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-common:2.4.1")
}

description = "Flink : Yarn"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
