/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-table-common"))
    implementation(project(":flink-sql-parser"))
    implementation(project(":flink-sql-parser-hive"))
    implementation(project(":flink-table-api-java"))
    implementation(project(":flink-table-api-scala_2.12"))
    implementation(project(":flink-table-api-java-bridge"))
    implementation(project(":flink-table-api-scala-bridge_2.12"))
    implementation(project(":flink-table-planner_2.12"))
    implementation(project(":flink-table-runtime_2.12"))
    implementation(project(":flink-cep"))
}

description = "Flink : Table : Uber"
