/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-metrics-prometheus"))
    testImplementation("com.squareup.okhttp3:okhttp:3.14.9")
    testImplementation("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
    testImplementation(project(":flink-end-to-end-tests-common"))
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : E2E Tests : Metrics reporter prometheus"
