/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-java"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-runtime-web"))
    implementation(project(":flink-optimizer"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-metrics-core"))
    implementation(project(":flink-container"))
    implementation(project(":flink-statebackend-rocksdb"))
    implementation(project(":flink-kubernetes"))
    implementation(project(":flink-yarn"))
    implementation(project(":flink-hadoop-fs"))
    implementation(project(":flink-mapr-fs"))
    testImplementation(project(":flink-test-utils-junit"))
    compileOnly(project(":flink-dist-scala_2.12"))
    compileOnly(project(":flink-examples-batch_2.12"))
    compileOnly(project(":flink-examples-streaming_2.12"))
    compileOnly(project(":flink-examples-streaming-state-machine_2.12"))
    compileOnly(project(":flink-examples-streaming-twitter_2.12"))
    compileOnly(project(":flink-gelly-examples_2.12"))
    compileOnly(project(":flink-examples-table_2.12"))
    compileOnly(project(":flink-external-resource-gpu"))
    compileOnly(project(":flink-metrics-dropwizard"))
    compileOnly(project(":flink-metrics-graphite"))
    compileOnly(project(":flink-metrics-influxdb"))
    compileOnly(project(":flink-metrics-prometheus"))
    compileOnly(project(":flink-metrics-jmx"))
    compileOnly(project(":flink-metrics-statsd"))
    compileOnly(project(":flink-metrics-datadog"))
    compileOnly(project(":flink-metrics-slf4j"))
    compileOnly(project(":flink-cep"))
    compileOnly(project(":flink-cep-scala_2.12"))
    compileOnly(project(":flink-gelly"))
    compileOnly(project(":flink-gelly-scala_2.12"))
    compileOnly(project(":flink-table-uber_2.12"))
    compileOnly(project(":flink-sql-client_2.12"))
    compileOnly(project(":flink-state-processor-api"))
    compileOnly(project(":flink-azure-fs-hadoop"))
    compileOnly(project(":flink-s3-fs-hadoop"))
    compileOnly(project(":flink-s3-fs-presto"))
    compileOnly(project(":flink-oss-fs-hadoop"))
    compileOnly(project(":flink-queryable-state-runtime"))
    compileOnly(project(":flink-python_2.12"))
    compileOnly("org.apache.flink:flink-shaded-netty-tcnative-dynamic:2.0.39.Final-14.0")
    compileOnly("javax.xml.bind:jaxb-api:2.3.1")
    compileOnly("javax.activation:javax.activation-api:1.2.0")
}

description = "Flink : Dist"
