/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    providedCompile(project(":flink-table-api-java-bridge"))
}

description = "Flink : E2E Tests : Batch SQL"
