/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    providedCompile(project(":flink-streaming-java"))
}

description = "Flink : E2E Tests : Parent Child classloading program"
