/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-hadoop-fs"))
    implementation("org.apache.hadoop:hadoop-common:2.4.1")
    implementation("org.apache.hadoop:hadoop-hdfs:2.4.1")
    testImplementation(project(":flink-core"))
}

description = "Flink : FileSystems : Mapr FS"
