/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("com.datastax.cassandra:cassandra-driver-core:3.0.0")
    implementation("io.netty:netty-handler:4.1.46.Final")
    implementation("com.datastax.cassandra:cassandra-driver-mapping:3.0.0")
    implementation("com.google.guava:guava:18.0")
    implementation("org.apache.flink:flink-shaded-guava:30.1.1-jre-14.0")
    testImplementation(project(":flink-runtime", "testArtifacts"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-tests"))
    testImplementation(project(":flink-test-utils"))
    testImplementation("org.apache.cassandra:cassandra-all:2.2.5")
    testImplementation("io.netty:netty-all:4.1.46.Final")
    implementation(project(":flink-scala_2.12"))
    implementation(project(":flink-streaming-scala_2.12"))
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-streaming-java", "testArtifacts"))
    implementation(project(":flink-table-api-java-bridge"))
    compileOnly(project(":flink-table-planner_2.12"))
    compileOnly("org.scala-lang:scala-library:2.12.7")
}

description = "Flink : Connectors : Cassandra"
