/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.apache.hbase:hbase-client:1.4.3")
    implementation("io.netty:netty-all:4.1.46.Final")
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-table-api-java-bridge"))
    compileOnly("org.apache.hadoop:hadoop-common:2.4.1")
}

description = "Flink : Connectors : HBase base"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
