/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-annotations"))
    implementation("com.google.guava:guava:30.0-jre")
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : Tools : CI : Java"
