/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-streaming-kafka-test-base"))
    implementation(project(":flink-connector-kinesis"))
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-end-to-end-tests-common"))
    implementation(project(":flink-connector-kinesis"))
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : E2E Tests : Streaming Kinesis"
