/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-hadoop-fs"))
    implementation(project(":flink-fs-hadoop-shaded"))
    implementation("org.apache.hadoop:hadoop-aliyun:3.2.2")
    implementation("com.aliyun.oss:aliyun-sdk-oss:3.4.1")
    testImplementation(project(":flink-fs-hadoop-shaded"))
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-hadoop-fs"))
    compileOnly(project(":flink-core"))
}

description = "Flink : FileSystems : OSS FS"
