/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-hbase-base"))
    implementation("io.netty:netty-all:4.1.46.Final")
    testImplementation(project(":flink-connector-hbase-base"))
    testImplementation(project(":flink-hadoop-compatibility_2.12"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation("org.apache.hbase:hbase-server:1.4.3")
    testImplementation("org.apache.hbase:hbase-server:1.4.3")
    testImplementation("org.apache.hbase:hbase-common:1.4.3")
    testImplementation("org.apache.hadoop:hadoop-minicluster:2.4.1")
    testImplementation("org.apache.hbase:hbase-hadoop-compat:1.4.3")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.4.1")
    testImplementation("org.apache.hbase:hbase-hadoop2-compat:1.4.3")
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-table-api-java-bridge"))
}

description = "Flink : Connectors : HBase 1.4"
