/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-examples-streaming_2.12"))
}

description = "Flink : Examples : Build Helper : Streaming State machine"
