/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-runtime"))
    providedCompile(project(":flink-runtime"))
}

description = "Flink : State backends : Heap spillable"
