/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-streaming-scala_2.12"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-connector-twitter"))
    implementation(project(":flink-connector-files"))
    implementation(project(":flink-connector-kafka"))
    implementation("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
    implementation(project(":flink-statebackend-rocksdb"))
    implementation("org.jcuda:jcuda:10.0.0") {
       	exclude("org.jcuda", "jcuda-natives")
    }
    implementation("org.jcuda:jcublas:10.0.0") {
       	exclude("org.jcuda", "jcuda-natives")
       	exclude("org.jcuda", "jcublas-natives")
    }
    testImplementation(project(":flink-test-utils"))
}

description = "Flink : Examples : Streaming"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
