/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("io.airlift.tpch:tpch:0.10")
}

description = "Flink : E2E Tests : TPCH"
