/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-hive_2.12"))
    implementation("org.apache.hive:hive-exec:2.3.6")
    implementation("org.antlr:antlr-runtime:3.5.2")
}

description = "Flink : Connectors : SQL : Hive 2.3.6"
