/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-rpc-core"))
    runtimeOnly(project(":flink-rpc-akka"))
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : RPC : Akka-Loader"
