/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-hadoop-fs"))
    implementation(project(":flink-fs-hadoop-shaded"))
    implementation(libs.hadoop.azure)
    testImplementation("com.microsoft.azure:azure:1.16.0")
    testImplementation(project(":flink-core"))
    compileOnly(project(":flink-core"))
}

description = "Flink : FileSystems : Azure FS Hadoop"
