/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-hive_2.12"))
    implementation("org.apache.hive:hive-exec:2.2.0") {
        exclude("org.pentaho", "pentaho-aggdesigner-algorithm")
    }
    implementation("org.apache.orc:orc-core:1.4.3")
    implementation("io.airlift:aircompressor:0.8")
    implementation("org.antlr:antlr-runtime:3.5.2")
}

description = "Flink : Connectors : SQL : Hive 2.2.0"
