/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-annotations"))
    implementation(project(":flink-core"))
    implementation(project(":flink-java"))
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-table-api-java"))
    implementation(project(":flink-sql-client_2.12"))
    implementation(project(":flink-metrics-prometheus"))
    implementation(project(":flink-metrics-influxdb"))
    implementation(project(":flink-runtime-web"))
    implementation(project(":flink-yarn"))
    implementation(project(":flink-kubernetes"))
    implementation("org.apache.flink:flink-shaded-netty:4.1.65.Final-14.0")
    implementation("org.apache.flink:flink-shaded-jackson-module-jsonSchema:2.12.4-14.0")
    implementation(project(":flink-statebackend-rocksdb"))
    implementation(project(":flink-python_2.12"))
    implementation(project(":flink-connector-pulsar"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation("org.jsoup:jsoup:1.14.2")
}

description = "Flink : Docs"
