/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-test-utils-junit"))
    providedCompile(project(":flink-core"))
}

description = "Flink : RPC : Core"
