/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("io.fabric8:kubernetes-client:5.5.0")
    testImplementation("io.fabric8:kubernetes-server-mock:5.5.0")
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-test-utils"))
    providedCompile(project(":flink-clients"))
    providedCompile(project(":flink-runtime"))
    compileOnly("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
}

description = "Flink : Kubernetes"
