/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-end-to-end-tests-common"))
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : E2E Tests : Metrics availability"
