/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation("org.apache.calcite:calcite-core:1.26.0")
    compileOnly(project(":flink-sql-parser"))
    compileOnly(project(":flink-table-common"))
    compileOnly("com.google.guava:guava:29.0-jre")
}

description = "Flink : Table : SQL Parser Hive"
