/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("com.google.cloud:google-cloud-core:1.93.7")
    implementation("com.google.cloud:google-cloud-pubsub:1.108.0")
    implementation("com.google.api.grpc:grpc-google-cloud-pubsub-v1:1.90.0")
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-runtime"))
    compileOnly(project(":flink-streaming-java"))
}

description = "Flink : Connectors : Google PubSub"
