/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-file-sink-common"))
    providedCompile(project(":flink-core"))
    compileOnly("org.apache.hadoop:hadoop-common:2.4.1")
    compileOnly("org.apache.hadoop:hadoop-hdfs:2.4.1")
}

description = "Flink : Formats : Compress"
