/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.apache.parquet:parquet-hadoop:1.11.1")
    implementation("org.apache.parquet:parquet-avro:1.11.1")
    implementation("org.apache.parquet:parquet-protobuf:1.11.1")
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-avro"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-connector-files"))
    testImplementation(project(":flink-file-sink-common"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-table-runtime_2.12"))
    compileOnly("org.apache.hadoop:hadoop-common:2.4.1")
    compileOnly("org.apache.hadoop:hadoop-mapreduce-client-core:2.4.1")
    compileOnly("it.unimi.dsi:fastutil:8.2.1")
}

description = "Flink : Formats : Parquet"
