/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation("org.apache.commons:commons-lang3:3.3.2")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("com.twitter:chill-java:0.7.6")
    testImplementation(project(":flink-test-utils-junit"))
}

description = "Flink : Java"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
