/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-hbase-base"))
    implementation("org.apache.hbase:hbase-client:2.2.3")
    implementation("io.netty:netty-all:4.1.46.Final")
    testImplementation(project(":flink-connector-hbase-base"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-hadoop-compatibility_2.12"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation("org.apache.hbase:hbase-server:2.2.3")
    testImplementation("org.apache.hbase:hbase-zookeeper:2.2.3")
    testImplementation("org.apache.hbase:hbase-common:2.2.3")
    testImplementation("org.apache.hbase:hbase-mapreduce:2.2.3")
    testImplementation("org.apache.hadoop:hadoop-minicluster:2.4.1")
    testImplementation("org.apache.hbase:hbase-hadoop-compat:2.2.3")
    testImplementation("org.apache.hadoop:hadoop-hdfs:2.4.1")
    testImplementation("org.apache.hbase:hbase-hadoop2-compat:2.2.3")
    providedCompile(project(":flink-core"))
    providedCompile(project(":flink-streaming-java"))
    providedCompile(project(":flink-table-api-java-bridge"))
    compileOnly("org.apache.hadoop:hadoop-common:2.4.1")
}

description = "Flink : Connectors : HBase 2.2"
