/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-streaming-kafka-test-base"))
    implementation(project(":flink-connector-kafka"))
    implementation(project(":flink-streaming-java"))
}

description = "Flink : E2E Tests : Streaming Kafka"
