/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-file-sink-common"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-java"))
    implementation("org.apache.flink:flink-shaded-guava:30.1.1-jre-14.0")
    implementation("org.apache.commons:commons-math3:3.6.1")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-runtime"))
}

description = "Flink : Streaming Java"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
