/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    compileOnly(project(":flink-table-common"))
    compileOnly(project(":flink-sql-avro"))
    compileOnly(project(":flink-json"))
    compileOnly(project(":flink-csv"))
    compileOnly(project(":flink-sql-connector-kafka"))
    compileOnly(project(":flink-sql-connector-kinesis"))
    compileOnly(project(":flink-sql-connector-elasticsearch6"))
    compileOnly(project(":flink-sql-connector-elasticsearch7"))
}

description = "Flink : E2E Tests : SQL client"
