/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
    id("org.apache.flink.java-conventions")
}

dependencies {
    api(project(":flink-annotations"))
    api(project(":flink-metrics-core"))
    implementation("org.apache.flink:flink-shaded-asm-7:7.1-14.0")
    implementation("org.apache.commons:commons-lang3:3.3.2")
    implementation("com.esotericsoftware.kryo:kryo:2.24.0")
    implementation("commons-collections:commons-collections:3.2.2")
    implementation("org.apache.commons:commons-compress:1.21")
    implementation("org.apache.flink:flink-shaded-guava:30.1.1-jre-14.0")
    testImplementation("com.github.luben:zstd-jni:1.4.9-1")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation("joda-time:joda-time:2.5")
    testImplementation("org.joda:joda-convert:1.7")
    testImplementation("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
    testImplementation("org.projectlombok:lombok:1.16.22")
}

description = "Flink : Core"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
