/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-hadoop-fs"))
    implementation("com.amazonaws:aws-java-sdk-core:1.11.951")
    implementation("com.amazonaws:aws-java-sdk-s3:1.11.951")
    implementation("com.amazonaws:aws-java-sdk-kms:1.11.951")
    implementation("com.amazonaws:aws-java-sdk-dynamodb:1.11.951")
    implementation("com.amazonaws:aws-java-sdk-sts:1.11.951")
    implementation(libs.hadoop.common)
    implementation(libs.hadoop.aws)
    compileOnly(project(":flink-core"))
}

description = "Flink : FileSystems : S3 FS Base"
