/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-java"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-core"))
    providedCompile(project(":flink-java"))
    providedCompile(project(":flink-scala_2.12"))
    compileOnly("org.apache.hadoop:hadoop-common:2.4.1")
    compileOnly("org.apache.hadoop:hadoop-mapreduce-client-core:2.4.1")
}

description = "Flink : Connectors : Hadoop compatibility"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
