/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("com.ververica:frocksdbjni:6.20.3-ververica-1.0")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-runtime"))
    providedCompile(project(":flink-streaming-java"))
    providedCompile(project(":flink-clients"))
}

description = "Flink : State backends : RocksDB"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
