/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-statebackend-rocksdb"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-runtime"))
    providedCompile(project(":flink-streaming-java"))
    providedCompile(project(":flink-java"))
}

description = "Flink : Libraries : State processor API"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
