/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-end-to-end-tests-common"))
    implementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-sql-connector-hbase-1.4"))
    testImplementation(project(":flink-sql-connector-hbase-2.2"))
    testImplementation(project(":flink-sql-client-test"))
    testImplementation("org.apache.hadoop:hadoop-common:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-yarn-client:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-yarn-api:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-minicluster:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-minikdc:3.2.0")
}

description = "Flink : E2E Tests : HBase"
