/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("io.prometheus:simpleclient:0.8.1")
    implementation("io.prometheus:simpleclient_httpserver:0.8.1")
    implementation("io.prometheus:simpleclient_pushgateway:0.8.1")
    testImplementation(project(":flink-metrics-core"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation("com.mashape.unirest:unirest-java:1.4.9")
    compileOnly(project(":flink-annotations"))
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-metrics-core"))
}

description = "Flink : Metrics : Prometheus"
