/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-optimizer"))
    compileOnly(project(":flink-java"))
    compileOnly(project(":flink-clients"))
    compileOnly("org.apache.commons:commons-lang3:3.3.2")
    compileOnly("org.apache.commons:commons-math3:3.6.1")
}

description = "Flink : Libraries : Gelly"
