/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-datastream-allround-test"))
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-statebackend-rocksdb"))
}

description = "Flink : E2E Tests : RocksDB state memory control"
