/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.influxdb:influxdb-java:2.17")
    testImplementation(project(":flink-metrics-core"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation("com.github.tomakehurst:wiremock:2.19.0")
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-metrics-core"))
}

description = "Flink : Metrics : InfluxDB"
