/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("org.scala-lang:scala-reflect:2.11.12")
    implementation("org.scala-lang:scala-library:2.11.12")
    implementation("org.scala-lang:scala-compiler:2.11.12")
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-end-to-end-tests-common"))
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-clients"))
}

description = "Flink : E2E Tests : Scala"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
