/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-parquet_2.12"))
}

description = "Flink : Formats : SQL Parquet"
