/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-streaming-java"))
    implementation(project(":flink-test-utils"))
    implementation("org.testcontainers:testcontainers:1.16.2")
}

description = "Flink : Test utils : Testing Framework"
