/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-dist_2.12"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-clients"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-yarn"))
    testImplementation(project(":flink-yarn"))
    testImplementation(project(":flink-examples-batch_2.12"))
    testImplementation(project(":flink-examples-streaming_2.12"))
    testImplementation("org.apache.hadoop:hadoop-common:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-yarn-client:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-yarn-api:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-minicluster:2.4.1")
    testImplementation("org.apache.hadoop:hadoop-minikdc:3.2.0")
}

description = "Flink : Yarn Tests"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
