/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-connector-test-utils"))
    compileOnly(project(":flink-core"))
}

description = "Flink : Connectors : Base"
