/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-core"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-optimizer"))
    implementation(project(":flink-java"))
    implementation("commons-cli:commons-cli:1.5.0")
    implementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-runtime"))
    testImplementation(project(":flink-core"))
}

description = "Flink : Clients"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
