/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("software.amazon.glue:schema-registry-serde:1.1.5")
    implementation("software.amazon.glue:schema-registry-common:1.1.5")
    implementation("software.amazon.awssdk:aws-core:2.17.52")
    implementation("com.kjetland:mbknor-jackson-jsonschema_2.12:1.0.39")
    implementation("com.github.erosb:everit-json-schema:1.12.2")
    compileOnly(project(":flink-core"))
    compileOnly(project(":flink-streaming-java"))
}

description = "Flink : Formats : JSON AWS Glue Schema Registry"
