/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-hive_2.12"))
    implementation("org.apache.hive:hive-exec:3.1.2")
    implementation("org.apache.thrift:libfb303:0.9.3")
    implementation("org.antlr:antlr-runtime:3.5.2")
    implementation("org.apache.hadoop:hadoop-mapreduce-client-core:3.1.0")
    implementation("org.apache.avro:avro:1.8.2")
    implementation("org.apache.avro:avro-mapred:1.8.2")
}

description = "Flink : Connectors : SQL : Hive 3.1.2"
