/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    testImplementation(project(":flink-metrics-core"))
    testImplementation(project(":flink-test-utils-junit"))
    testImplementation(project(":flink-test-utils"))
    providedCompile(project(":flink-annotations"))
    providedCompile(project(":flink-core"))
    providedCompile(project(":flink-metrics-core"))
}

description = "Flink : Metrics : JMX"
