/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-s3-fs-base"))
    implementation("com.facebook.presto:presto-hive:0.257")
    implementation("com.facebook.presto.hadoop:hadoop-apache2:2.7.4-9")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-hadoop-fs"))
    compileOnly(project(":flink-core"))
    compileOnly("javax.xml.bind:jaxb-api:2.3.1")
}

description = "Flink : FileSystems : S3 FS Presto"
