/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-format-common"))
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-planner_2.12"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-table-planner_2.12"))
    compileOnly("org.apache.flink:flink-shaded-jackson:2.12.4-14.0")
    providedCompile(project(":flink-core"))
    providedCompile(project(":flink-table-common"))
}

description = "Flink : Formats : Csv"
