/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation(project(":flink-connector-kafka"))
    implementation(project(":flink-avro"))
    implementation(project(":flink-avro-confluent-registry"))
    providedCompile(project(":flink-streaming-java"))
}

description = "Flink : E2E Tests : Confluent schema registry"
