/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
}

dependencies {
    implementation("com.amazonaws:aws-java-sdk-kinesis:1.12.7")
    implementation("com.amazonaws:aws-java-sdk-sts:1.12.7")
    implementation("com.amazonaws:aws-java-sdk-kms:1.12.7")
    implementation("com.amazonaws:aws-java-sdk-s3:1.12.7")
    implementation("com.amazonaws:aws-java-sdk-dynamodb:1.12.7")
    implementation("com.amazonaws:aws-java-sdk-cloudwatch:1.12.7")
    implementation("com.amazonaws:amazon-kinesis-producer:0.14.1")
    implementation("com.amazonaws:amazon-kinesis-client:1.14.1")
    implementation("com.amazonaws:dynamodb-streams-kinesis-adapter:1.5.3")
    implementation("com.google.guava:guava:29.0-jre")
    implementation("software.amazon.awssdk:kinesis:2.16.86")
    implementation("software.amazon.awssdk:netty-nio-client:2.16.86")
    implementation("software.amazon.awssdk:sts:2.16.86")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation("org.apache.httpcomponents:httpcore:4.4.14")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.13.0")
    testImplementation("com.amazonaws:amazon-kinesis-aggregator:1.0.3")
    testImplementation(project(":flink-core"))
    testImplementation(project(":flink-streaming-java"))
    testImplementation(project(":flink-tests"))
    testImplementation(project(":flink-connector-testing"))
    testImplementation(project(":flink-test-utils"))
    testImplementation(project(":flink-runtime"))
    testImplementation("org.testcontainers:testcontainers:1.16.2")
    testImplementation(project(":flink-table-common"))
    testImplementation(project(":flink-table-planner_2.12"))
    compileOnly("javax.xml.bind:jaxb-api:2.3.1")
    compileOnly(project(":flink-streaming-java"))
    compileOnly(project(":flink-table-api-java-bridge"))
}

description = "Flink : Connectors : Kinesis"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
